server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/restart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Tct241904
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true